"""empty message

Revision ID: 623515ab324c
Revises: e20033f8a2fe
Create Date: 2020-05-28 14:41:33.381852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623515ab324c'
down_revision = 'e20033f8a2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=20))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=1))
    # ### end Alembic commands ###
