"""empty message

Revision ID: e20033f8a2fe
Revises: 4af7c632d3a6
Create Date: 2020-05-21 20:35:29.093807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20033f8a2fe'
down_revision = '4af7c632d3a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actors', sa.Column('seeking_work', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('actors', 'seeking_work')
    # ### end Alembic commands ###
